#!/usr/bin/env php
<?php

const ROOT_DIR = __DIR__;

require __DIR__.'/vendor/autoload.php';

use JackedPhp\JackedServer\Commands\CompilePharCommand;
use JackedPhp\JackedServer\Commands\RunCommand;
use Symfony\Component\Console\Application;

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

$application = new Application;

$application->add(new RunCommand);
$application->add(new CompilePharCommand);

$application->run();
