#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use JackedPhp\JackedServer\Commands\RunCommand;
use Symfony\Component\Console\Application;

define('IS_PHAR', str_starts_with(__DIR__, 'phar:///'));
define('ROOT_DIR', IS_PHAR ? getcwd() : __DIR__);
define('CONFIG_FILE',  __DIR__ . '/config/jacked-server.php');
const MONITOR_CHANNEL = 'jacked-monitor';

$application = new Application;

$application->add(new RunCommand('run'));
$application->setDefaultCommand('run', true);

$application->run();
