name: WordsTree
description: Prepare WordsTree details.
runs:
  using: composite
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: openswoole, curl, pcntl
        coverage: none
        tools: composer, phpunit
      env:
        fail-fast: true

    - name: Validate composer.json and composer.lock
      shell: bash
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      shell: bash
      run: composer install --prefer-dist --no-progress

    - name: Keep only php-fpm 8.3
      shell: bash
      run: |
        sudo service php8.1-fpm stop
        sudo service php8.3-fpm stop
        sudo ps aux | grep php-fpm
        sudo service php8.3-fpm start

    - name: Copy jacked server to linux host place
      shell: bash
      run: |
        sudo cp -r ${{ github.workspace }} /var/www/jacked-server
        sudo chown -R www-data /var/www/jacked-server
