name: PHP Composer

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:

  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
        ports:
          - 33061:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare Environment
        uses: ./.github/actions/prepare-environment

      - name: Run test suite
        shell: bash
        run: |
          cd /var/www/jacked-server
          sudo -u www-data -- vendor/bin/phpunit
